// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniSupermarket.API.Data;

#nullable disable

namespace MiniSupermarket.API.Migrations
{
    [DbContext(typeof(SupermarketDbContext))]
    [Migration("20261001121914_AddCustomersTable")]
    partial class AddCustomersTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Gạo, Nếp & Cốc loại",
                            Description = "Gạo ST25, gạo nở, nếp nương, đậu xanh, đậu đỏ"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Gia vị & Dầu ăn",
                            Description = "Nước mắm, nước tương, hạt nêm, đường, dầu ăn"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Mì, Phở & Thực phẩm ăn liền",
                            Description = "Mì gói, phở khô, bún tươi, hủ tiếu, cháo ăn liền"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Bánh kẹo & Đồ ăn vặt",
                            Description = "Bánh quy, kẹo dẻo, snack, hạt điều, mứt"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Nước giải khát & Trà",
                            Description = "Nước ngọt, nước khoáng, trà túi lọc, cà phê hòa tan"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Sữa & Sản phẩm từ sữa",
                            Description = "Sữa tươi, sữa đặc, sữa chua, phô mai"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Thực phẩm đóng hộp",
                            Description = "Cá hộp, thịt hộp, pate, ngô ngọt đóng hộp"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Hóa mỹ phẩm & Tắm giặt",
                            Description = "Xà bông, dầu gội, nước rửa chén, nước lau nhà, bột giặt"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Vệ sinh cá nhân",
                            Description = "Kem đánh răng, bàn chải, khăn giấy, khẩu trang"
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "Đồ dùng gia đình & Gia dụng",
                            Description = "Băng dính, túi rác, màng bọc thực phẩm, chổi, khăn lau"
                        },
                        new
                        {
                            CategoryId = 11,
                            CategoryName = "Thực phẩm khô & Nông sản",
                            Description = "Nấm hương, mộc nhĩ, tôm khô, măng khô"
                        },
                        new
                        {
                            CategoryId = 12,
                            CategoryName = "Gia vị tươi & Đồ sơ chế",
                            Description = "Hành, tỏi, ớt, sả, gừng đóng gói"
                        },
                        new
                        {
                            CategoryId = 13,
                            CategoryName = "Đồ uống có cồn & Bia",
                            Description = "Bia lon, rượu nếp, rượu vang"
                        },
                        new
                        {
                            CategoryId = 14,
                            CategoryName = "Đồ mẹ và bé",
                            Description = "Tã bỉm, tăm bông em bé, khăn giấy ướt"
                        },
                        new
                        {
                            CategoryId = 15,
                            CategoryName = "Nến, Hương & Đồ thờ cúng",
                            Description = "Hương thắp, nến cốc, giấy cúng gia đình"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MembershipRank")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<int>("RewardPoints")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "123 Lê Lợi, Q1",
                            CustomerName = "Nguyễn Văn A",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0901122334",
                            RewardPoints = 150
                        },
                        new
                        {
                            CustomerId = 2,
                            Address = "456 Nguyễn Huệ, Q1",
                            CustomerName = "Trần Thị B",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0918877665",
                            RewardPoints = 50
                        },
                        new
                        {
                            CustomerId = 3,
                            Address = "789 Điện Biên Phủ, Q3",
                            CustomerName = "Lê Văn C",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0983344556",
                            RewardPoints = 10
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Barcode = "8935001001",
                            CategoryId = 1,
                            Price = 180000m,
                            ProductName = "Gạo Ông Thọ ST25 5kg",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 2,
                            Barcode = "8935001002",
                            CategoryId = 2,
                            Price = 32000m,
                            ProductName = "Nước mắm Nam Ngư 500ml",
                            StockQuantity = 120
                        },
                        new
                        {
                            ProductId = 3,
                            Barcode = "8935001003",
                            CategoryId = 3,
                            Price = 115000m,
                            ProductName = "Mì Hảo Hảo Tôm Chua Cay (Thùng 30 gói)",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 4,
                            Barcode = "8935001004",
                            CategoryId = 4,
                            Price = 18000m,
                            ProductName = "Bánh quy OREO vị Vani 133g",
                            StockQuantity = 80
                        },
                        new
                        {
                            ProductId = 5,
                            Barcode = "8935001005",
                            CategoryId = 5,
                            Price = 10000m,
                            ProductName = "Nước khoáng Lavie 1.5L",
                            StockQuantity = 150
                        },
                        new
                        {
                            ProductId = 6,
                            Barcode = "8935001006",
                            CategoryId = 6,
                            Price = 38000m,
                            ProductName = "Sữa tươi Vinamilk Có Đường 1L",
                            StockQuantity = 60
                        },
                        new
                        {
                            ProductId = 7,
                            Barcode = "8935001007",
                            CategoryId = 7,
                            Price = 28000m,
                            ProductName = "Cá ngừ ngâm dầu Hạ Long 175g",
                            StockQuantity = 45
                        },
                        new
                        {
                            ProductId = 8,
                            Barcode = "8935001008",
                            CategoryId = 8,
                            Price = 30000m,
                            ProductName = "Nước rửa chén Sunlight Chanh 750ml",
                            StockQuantity = 90
                        },
                        new
                        {
                            ProductId = 9,
                            Barcode = "8935001009",
                            CategoryId = 9,
                            Price = 25000m,
                            ProductName = "Kem đánh răng PS Bảo Vệ 123 180g",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = 10,
                            Barcode = "8935001010",
                            CategoryId = 10,
                            Price = 35000m,
                            ProductName = "Túi rác tự hủy sinh học 1kg",
                            StockQuantity = 75
                        },
                        new
                        {
                            ProductId = 11,
                            Barcode = "8935001011",
                            CategoryId = 11,
                            Price = 45000m,
                            ProductName = "Nấm hương khô Cao Bằng 100g",
                            StockQuantity = 30
                        },
                        new
                        {
                            ProductId = 12,
                            Barcode = "8935001012",
                            CategoryId = 12,
                            Price = 22000m,
                            ProductName = "Tỏi Lý Sơn đóng gói 200g",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 13,
                            Barcode = "8935001013",
                            CategoryId = 13,
                            Price = 105000m,
                            ProductName = "Bia Tiger Lon 330ml (Lốc 6 lon)",
                            StockQuantity = 35
                        },
                        new
                        {
                            ProductId = 14,
                            Barcode = "8935001014",
                            CategoryId = 14,
                            Price = 42000m,
                            ProductName = "Khăn giấy ướt Bobby 100 tờ",
                            StockQuantity = 65
                        },
                        new
                        {
                            ProductId = 15,
                            Barcode = "8935001015",
                            CategoryId = 15,
                            Price = 25000m,
                            ProductName = "Hương trầm thảo mộc cao cấp 100 nén",
                            StockQuantity = 85
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.HasOne("MiniSupermarket.API.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
